### ISSUE TITLE
Query param vs. path param, best way to integrate with front end

### ISSUE THREAD

**Issue by sbauch** [salsify/omniauth-multi-provider#11]
Due to the fact that this strategy uses a path param for the `identity_provider_id`, I feel like I need to make an extra request / controller action in order to build a SAML login form.

A pretty common approach to SAML login UX is to offer a secondary form that has an input for domain or email. The application then persists SAML config settings per tenant with the domain as a key, and when this login form is submitted, uses the domain to surface the relevant SAML settings and redirect the user.

Rails doesn't really support the idea of posting a form to a URL based on the value of an input - I could use JS to change the form's action but that feels pretty hacky.

If instead of the path param and regex approach, would it be possible to use a query param, such that the form submission would include the `identity_provider_id` directly from the form submit?

I'm currently working around this by posting to another controller action which takes the form submission and redirects to the authorize route:
```ruby
  def idp
    # I'm fine using the domain string as the "id" but of course could do a database lookup here and pass a UUID.
    identity_provider_id = params[:email].split('@').last
    
    redirect_to(
      user_omniauth_authorize_path(identity_provider_id: identity_provider_id)
    )
  end
```

This also requires using a get request for the request phase, whereas my understanding is that OmniAuth is deprecating get requests - https://github.com/omniauth/omniauth/releases/tag/v2.0.0

Any tips for how best to hit these routes from the frontend? Thoughts on a different approach to better support OmniAuth 2.0 and POST-only request phase?

**Comment by sbauch** [comment]
FWIW I'm working on a blog post that uses this library, and just want to show the library in a good light, so any thoughts on this issue would be appreciated! 

https://deploy-preview-44--osso.netlify.app/blog/saml-sso-rails

**Comment by jturkel** [comment]
The core of this gem implemented in [OmniAuth::MultiProvider::Handler](https://github.com/salsify/omniauth-multi-provider/blob/master/lib/omni_auth/multi_provider/handler.rb) really assumes that the identity provider ID is in the path. It's been awhile but I believe we did it this way since we wanted to support identity provider initiated authentication (in addition to service provider initiated authentication) and there were some identity providers at the time that didn't support callback URLs with query parameters. I could be misremembering though.

If you're only interested in supporting multiple SAML providers via query parameters, you could try using omni-auth directly with a strategy that subclasses [OmniAuth::Strategies::SAML](https://github.com/omniauth/omniauth-saml/blame/master/lib/omniauth/strategies/saml.rb) and overrides the `with_settings` method to lookup the identity provider's settings based on a query parameter in the Rack env (accessible via `@env`).

**Comment by sbauch** [comment]
Ok I'll look into that approach! Thanks.
